### ISSUE TITLE
RagdollView isn't supported anymore?

### ISSUE THREAD

**Issue by TiberianErin** [Lakatrazz/RagdollPlayer#2]
I'm not motion sick in VR. Like. Ever.

RagdollView would be so much fun to me.

But, alas. It is not updated. And as far as I know, it doesn't continue to work in Patch 5.
There isn't even a visible github repo for it. A shame. I couldn't find anywhere else to post this issue. So, RagdollPlayer seems the most relevant.

Please, do something. Some of us actually _like_ getting our cameras jerked out of control.

Thank you for your time.

**Comment by Lakatrazz** [comment]
I am aware it's not updated, I am going to update all of my mods eventually but currently do not have the time and with patch #6 releasing in a week will not be doing it soon

**Comment by TiberianErin** [comment]
Alright, thanks for the reassurance.
