### ISSUE TITLE
Ragdoll arms

### ISSUE THREAD

**Issue by SoldierThree57** [Lakatrazz/RagdollPlayer#5]
The ragdoll mods arms wont work will I play with friends on fusion, do I need to enable anything. Yes im on full pcvr steam

**Comment by Lakatrazz** [comment]
Arm control is not synced in fusion.

**Comment by TiberianErin** [comment]
> Arm control is not synced in fusion.

But it used to be, right? I do remember using arm control in fusion a while back. Then it was gone, now it's back but not with fusion support.

Will fusion support ever be re-added for arm control?

**Comment by TiberianErin** [comment]
still waiting for an update and/or reason so as to why it's broken and won't be fixed :3
